services:
  create_csv:
    image: bakvivas/create_csv:test
    container_name: create_csv
    volumes: 
      - /var/lib/DB_test:/var/lib/DB_test
    env_file:
      - .env

  send_data:
    image: bakvivas/send_data:test
    depends_on: 
      - create_csv
    environment:
      - INSTANCE_ID=$HOSTNAME
    volumes:
      - /var/lib/DB_test:/var/lib/DB_test
    entrypoint: ["/bin/sh", "-c", "/var/lib/DB_test/wait_create_csv.sh"]
    env_file:
      - .env.database
