version: '3.8'

services:
  create_csv:
    image: bakvivas/create_csv:test
    container_name: create_csv
    volumes: 
      - /var/lib/DB_test:/var/lib/DB_test
    env_file:
      - .env
  send_data:
    image: bakvivas/send_data:test
    container_name: send_data
    environment:
      - INSTANCE_ID=$HOSTNAME
    volumes:
      - /var/lib/DB_test:/var/lib/DB_test
    env_file:
      - .env.database
